version: '3'

tasks:
  desc: "start the project (for web-development only)"
  start:
    cmds:
      - npm run start

  build:
    desc: "build the project and move the production artifact into the deployment folder (for production only)"
    cmds:
      - npm run build --production
      - cp -Rf ./build/* ../cps-frontend-static
      - rm -Rf ./build

  deploy:
    desc: "build a docker image specific only to https://cpsapp.ca domain and push to dockerhub repo so this image can be used in production container."
    cmds:
      - docker build -f prod.Dockerfile -t rodolfossp/cps-frontend:prod-latest --platform linux/amd64 --build-arg REACT_APP_API_HOST=https://cpsdata.ca --build-arg REACT_APP_API_DOMAIN=cpsdata.ca --build-arg REACT_APP_API_PROTOCOL=https --build-arg REACT_APP_WWW_DOMAIN=cpsapp.ca --build-arg REACT_APP_WWW_PROTOCOL=https .
      - docker tag rodolfossp/cps-frontend:prod-latest rodolfossp/cps-frontend:prod-latest
      - docker push rodolfossp/cps-frontend:prod-latest
