version: '3'

tasks:
  desc: "start the project (for web-development only)"
  start:
    cmds:
      - npm run start

  build:
    desc: "build the project and move the production artifact into the deployment folder (for production only)"
    cmds:
      - npm run build
      - cp -Rf ./build/* ../cps-frontend-static
      - rm -Rf ./build
